### PR TITLE
Refactor to class methods. No reason to create an instance for this.

### PR DESCRIPTION
**Pull request by jonmarimba**
Hi @dav 

I work with @dillan, whose PR was your most recent merge. I don't see a strong argument to instantiate an object for this, rather these are probably more appropriately class methods. I refactored to class methods, updated the demo project, and updated the readme to match.

Cheers,
@jonmarimba

### CODE REVIEW

**Comment by dav** [comment]
Seems legit. Thanks for the update.

**Comment by jonmarimba** [comment]
Thanks @dav. I noticed I forgot to remove this in the readme:

[loremIpsum release];

Would you like a new PR for that or do you want to make the quick fix yourself?

**Comment by dav** [comment]
No, worries. I'll do it.

**Comment by dillan** [comment]
It was quick. See https://github.com/dav/Objective-C-Lorem-Ipsum-Generator/pull/6

**Comment by dillan** [comment]
You beat me to it. :) Thanks @dav!

**Pull request merged**
